executables:
 AppM-exe:
   main:                main.hs
   source-dirs:         .
   ghc-options:
   - -threaded
   - -rtsopts
   - -with-rtsopts=-N
   dependencies:
   - base
   - text
   - webappm
   - process


